services:
  db:
    image: postgres:18
    container_name: banco-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ipdesenvolvimento
      POSTGRES_PASSWORD: ipdesenvolvimento
      POSTGRES_DB: sistema_academico_development
    volumes:
      - turmaria_pgdata:/var/lib/postgresql  # sem /data

volumes:
  turmaria_pgdata:
